# ---------------------------
# Hexo Theme Solitude
# Author: EverFu
# Github: https://github.com/everfu/hexo-theme-solitude
#
# é…ç½®æŒ‡å—: https://solitude.js.org/
# ä½ å¯ä»¥ä»æŒ‡å—ä¸­è·å¾—æ›´è¯¦ç»†çš„è¯´æ˜
#
# Guide: https://solitude.js.org/
# You can get more detailed help from the guide
#
# èµåŠ©ï¼šhttps://www.patreon.com/everfu
# sponsor: https://www.patreon.com/everfu
# ---------------------------

site:
  name:
    class: text
    custom: Solitude
  siteIcon: /img/pwa/favicon.ico
  icon: /img/pwa/favicon.ico

nav:
  group:
    # é¡¹ç›®: # åˆ†ç±»åç§°
    #   Solitude: https://github.com/everfu/hexo-theme-solitude || /img/pwa/favicon.ico # å­èœå•åç§°(submenu name): é“¾æ¥åœ°å€(address) || å›¾æ ‡(icon)
  menu:
    # é¦–é¡µ: / # æ˜¾ç¤ºåç§°ï¼šè·¯å¾„ / Display name: path
    # æ–‡åº“: # æ˜¾ç¤ºåç§° / Display name
    #   æ–‡ç« åˆ—è¡¨: /archives/ || fas fa-folder-closed # å­èœå•åç§°ï¼šè·¯å¾„ || å›¾æ ‡ / Submenu name: path || icon
    #   å…¨éƒ¨åˆ†ç±»: /categories/ || fas fa-clone
    #   å…¨éƒ¨æ ‡ç­¾: /tags/ || fas fa-tags
    # å‹é“¾:
    #   å‹é“¾é±¼å¡˜: /moments/ || fas fa-wifi
    #   å‹æƒ…é“¾æ¥: /links/ || fas fa-user-group
    #   å®è—åšä¸»: javascript:travelling() || fas fa-gift
    # æˆ‘çš„:
    #   è£…å¤‡: /equipment/ || fas fa-laptop
    #   å·¥å…·ç®±: /tlink/ || fas fa-toolbox
    #   éŸ³ä¹é¦†: /music/ || fas fa-music
    # å…³äº:
    #   å…³äºæœ¬ç«™: /about/ || fas fa-user
  right:
    random: false # éšæœºæ–‡ç« è·³è½¬ / random post button
    console: false # æ§åˆ¶å° / console
    custom:
      # - name: å¼€å¾€ - å‹é“¾æ¥åŠ› # æ˜¾ç¤ºæ–‡å­— / Displayed text
      #   url: https://www.travellings.cn/go.html # è·³è½¬é“¾æ¥ / Jump link
      #   icon: fas fa-train # å›¾æ ‡ / Icon
      #   onclick: # ç‚¹å‡»äº‹ä»¶ / Click event
      #   id: travellings_button # id

hometop:
  enable: false
  banner:
    title: å®é™è‡´è¿œ<br>çƒ­çˆ±ç”Ÿæ´»
    url: Hexo Theme Solitude
    icon:
      # HTML: # åå­— / Name
      #   img: https://7.isyangs.cn/34/65f2e42921677-34.png # å›¾ç‰‡ / Image
      #   color: "#e9572b" # èƒŒæ™¯è‰² / Background color
      # JS:
      #   img: https://7.isyangs.cn/34/65f2e43ceddda-34.png
      #   color: "#f7cb4f"
      # Docker:
      #   img: https://7.isyangs.cn/34/65f2e45462045-34.png
      #   color: "#57b6e6"
      # Flutter:
      #   img: https://7.isyangs.cn/34/65f2e47acbe98-34.png
      #   color: "#ffffff"
      # WebPack:
      #   img: https://7.isyangs.cn/34/65f2e488bf8ed-34.png
      #   color: "#2e3a41"
      # Git:
      #   img: https://7.isyangs.cn/34/65f2e499066fa-34.png
      #   color: "#df5b40"
  group:
    # çƒ­é—¨: /tags/çƒ­é—¨/ || fas fa-fire || linear-gradient(to right, #f65, #ffbf37)
    # æ•™ç¨‹: /tags/æ•™ç¨‹/ || fas fa-book || linear-gradient(to right, #358bff, #15c6ff)
    # ç²¾é€‰: /tags/ç²¾é€‰/ || fas fa-star || linear-gradient(to right, #18e7ae, #1eebeb)
  recommendList:
    sup: Top
    title: Solitude Documentation
    url: https://solitude.js.org/
    img: /img/default.avif
    color: "none"

carousel: false

aside:
  # å€¼ï¼šaboutï¼ˆå…³äºæˆ‘ï¼‰ã€newestPostï¼ˆæœ€æ–°æ–‡ç« ï¼‰ã€allInfoï¼ˆç½‘ç«™ä¿¡æ¯ï¼‰ã€flipï¼ˆå…¬ä¼—å·äºŒç»´ç ï¼‰ã€newest_commentï¼ˆæœ€æ–°è¯„è®ºï¼‰
  # Values: about (info card), newestPost (latest article), allInfo (website information), flip (official account QR code), newest_comment (latest comment)
  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  position: 1 # left(0): å·¦ä¾§ / right(1): å³ä¾§
  card:
    style: 0 # 0: Heoæ ·å¼ ï¼š1: è®¾è®¡æ ·å¼
    author:
      img: /img/avatar.avif
      sticker:
    url: /about/
    background: # https://s3.qjqq.cn/47/663af296b85f4.webp!color # ä¸è®¾ç½®ä¸ä¼šå±•ç¤ºï¼ˆä»…æ ·å¼ä¸º1ã€2æ—¶æœ‰æ•ˆï¼‰
    content: åˆ†äº«è‡ªå·±å¯¹ç¼–ç¨‹çš„<b>çƒ­çˆ±</b>ï¼Œå¯¹ç¾å¥½ç”Ÿæ´»çš„<b>å‘å¾€</b>ï¼Œå¯¹çŸ¥è¯†æµ·æ´‹<b>æ¢ç´¢å†ç¨‹</b>ã€‚ # æ ·å¼ä¸º1æ—¶æ— æ•ˆ
    content2: ç›¸ä¿¡ä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°å¯¹ä½ æœ‰ç”¨çš„çŸ¥è¯†å’Œæ•™ç¨‹ã€‚ # æ ·å¼ä¸º1æ—¶æ— æ•ˆ
    sayhello:
      morning: ä¸€æ—¥ä¹‹è®¡åœ¨äºæ™¨
      noon: åƒé¥±äº†æ‰æœ‰åŠ›æ°”å¹²æ´»
      afternoon: é›†ä¸­ç²¾åŠ›ï¼Œæ”»å…‹éš¾å…³
      night: ä¸è¦å¤ªåŠ³ç´¯äº†ï¼Œæ—©ç¡æ›´å¥åº·
      goodnight: ç¡ä¸ªå¥½è§‰ï¼Œä¿è¯ç²¾åŠ›å……æ²›
    sayhello2:
      # - ğŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
      # - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
      # - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
      # - ğŸ”¨ è®¾è®¡å¼€å‘ä¸€æ¡é¾™
      # - ğŸ¤ ä¸“ä¿®äº¤äº’ä¸è®¾è®¡
      # - ğŸƒ è„šè¸å®åœ°è¡ŒåŠ¨æ´¾
      # - ğŸ§± å›¢é˜Ÿå°ç»„å‘åŠ¨æœº
      # - ğŸ’¢ å£®æ±‰äººç‹ è¯ä¸å¤š
      # - ğŸ® ç”µç«æ¸¸æˆçˆ±å¥½è€…
    information:
      # Github: https://github.com/everfu || fas fa-github # åç§°ï¼šé“¾æ¥ || å›¾æ ‡ / Name: link || icon
      # Bilibili: https://space.bilibili.com/1329819902 || fas fa-bilibili
  flip:
    favicon:
    face:
    backface:
    backcolor: "var(--efu-blue)"
  newest_comment:
    enable: true
    storage: .5 # ç¼“å­˜æ—¶é—´ 1: 1å¤© / .5 : åŠå¤© / Cache time 1: 1 day .5 : half a day
    limit: 5 # è¯„è®ºæ•° / Number of comments
  toc:
    post: true
    page: false
    vague: true
  tags:
    enable: false
    limit: 20
    highlight_list:
    #  - Hexo
  archive:
    enable: false
    type: "month" # month: æŒ‰æœˆ / year: æŒ‰å¹´ : month: by month / year: by year
  siteinfo:
    postcount: true
    wordcount: false
    pv: true
    uv: true
    updatetime: true
    runtimeenable: true
    runtime: "2023-04-20 00:00:00"

index_post_list:
  direction: column # row / column
  column: 2 # 2:2åˆ— 3:3åˆ—
  content: false # 1: post.description / 2: è‡ªåŠ¨è·å–descriptionæˆ–æˆªå–å†…å®¹(Automatically get descriptions or screenshots) / 3: åªä½¿ç”¨æˆªå–å†…å®¹(Use only screenshots) / false: ä¸æ˜¾ç¤ºå†…å®¹(No content is displayed)
  length: 500 # æˆªå–å†…å®¹çš„é•¿åº¦ : The length of the screenshot content
  cover: both # left: åœ¨å·¦ä¾§ : left / right: åœ¨å³ä¾§ : right / both: ä¸¤ä¾§ : both

page:
  error: true # 404é¡µé¢ / 404 page
  tags: true # æ ‡ç­¾é¡µ / Tags page
  categories: true # åˆ†ç±»é¡µ / Categories page
  default: # é»˜è®¤å€¼ / Default value
    cover:
      # - /img/default.png # é»˜è®¤å›¾ç‰‡ / default cover

post:
  default:
    top_cover: true # é¡¶éƒ¨æè¿° / Top description
    cover:
      # -  # é»˜è®¤å›¾ç‰‡ / default cover
    locate: China
    copyright:
      enable: true
      author:
        url: /about/ # ç‚¹å‡»å¤´åƒè·³è½¬åœ°å€
        img: # æ˜¾ç¤ºå¤´åƒï¼Œä¸å¡«å†™é»˜è®¤æ˜¾ç¤ºsite_icon
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  meta:
    date: false # å‘å¸ƒæ—¥æœŸ / Release date
    updated: false # æ›´æ–°æ—¥æœŸ / Update date
    locate: false # ä½ç½® / Location
    wordcount: false # å­—æ•° / Number of words
    readtime: false # è®¿é—® / uv
    pv: false # æµè§ˆé‡ / pv
    comment: false # è¯„è®ºæ•° / Comment count
  award:
    enable: false
    appreciators: /about # èµèµè®°å½• / Appreciative records
    title: æ„Ÿè°¢æ‚¨çš„èµèµã€‚
    desc: å› ä¸ºæœ‰ä½ ä»¬çš„æ”¯æŒï¼Œæˆ‘æ‰ä½“ä¼šåˆ°å†™æ–‡ç« çš„ä»·å€¼ã€‚
    list:
      # - name: Github Sponsor
      #   qcode: https://s3.qjqq.cn/47/661ba900c4bc1.webp!color
      #   url: https://github.com/sponsors/efuo
      #   color: var(--efu-black)
    share:
      enable: false
      list:
      # - qq
      # - weibo
      # - twitter
      # - facebook
      # - telegram
      # - whatsapp
      # - linkedin
      # - link
      # - qrcode
  rss: # /atom.xml
  covercolor:
    enable: false
    mode: local # localï¼šæœ¬åœ°å–è‰² / apiï¼šimg2colorå–è‰² : local: local color / api: img2color color
    api: https://api.qjqq.cn/api/Imgcolor?img= # apiåœ°å€ / api address
    time: 43200000 # apiå–è‰²é—´éš”ï¼ˆæ¯«ç§’ï¼‰ï¼Œé»˜è®¤ä¸º12å°æ—¶ / api color interval (milliseconds), default is 12 hours
  # footer
  footer:
    enable: true
    desc: æ¥è‡ª Efu çš„æ–‡ç«  # ä»‹ç»æ–‡å­—
    button: # è·³è½¬æŒ‰é’®
      enable: true
      name: äº†è§£æ›´å¤š
      url: /about/

theme_color:
  dark: "#ffc848" # æš—è‰²æ¨¡å¼ / Dark mode
  dark_op: "#f2b94b23" # æš—è‰²æ¨¡å¼é€æ˜ / Dark mode transparent
  dark_op_deep: "#f2b94bdd" # æš—è‰²æ¨¡å¼é€æ˜æ·±è‰² / Dark mode transparent dark
  dark_none: "#f2b94b00" # æš—è‰²æ¨¡å¼é€æ˜æ— è‰² / Dark mode transparent colorless
  light: "#425AEF" # äº®è‰²æ¨¡å¼ / Light mode
  light_op: "#4259ef23" # äº®è‰²æ¨¡å¼é€æ˜ / Light mode transparent
  light_op_deep: "#4259efdd" # äº®è‰²æ¨¡å¼é€æ˜æ·±è‰² / Light mode transparent dark
  light_none: "#4259ef01" # äº®è‰²æ¨¡å¼é€æ˜æ— è‰² / Light mode transparent colorless
display_mode:
  type: auto # auto: è‡ªåŠ¨åˆ‡æ¢ / dark: æš—è‰²æ¨¡å¼ / light: äº®è‰²æ¨¡å¼ / auto: automatic switching / dark: dark mode / light: light mode
  universe: true # å¼€å¯åæš—è‰²æ¨¡å¼ä¸‹ä¼šæ˜¾ç¤ºæ˜Ÿç©ºèƒŒæ™¯ / After opening, the dark mode will display the starry sky background

related_post:
  enable: false
  limit: 2
  date_type: created

footer:
  information:
    author: false # æ˜¯å¦æ˜¾ç¤º site_icon / enable site_icon in footer
    left:
      # Github: https://github.com/efuo || fas fa-github # åç§°ï¼šé“¾æ¥ || å›¾æ ‡ / Name: link || icon
      # Mail: mailto:o@efu.me || fas fa-envelope
    right:
      # Bilibili: https://space.bilibili.com/1329819902 || fas fa-bilibili
      # æŠ–éŸ³: https://v.douyin.com/iJsLc8jt/ || fas fa-tiktok
  group:
    # å¯¼èˆª:
    #   å½’æ¡£: /archives/
    #   åˆ†ç±»: /categories/
    #   æ ‡ç­¾: /tags/
    # æœåŠ¡:
    #   é˜¿é‡Œäº‘: https://aliyun.com/
    #   51laç»Ÿè®¡: https://v6.51.la/
    #   ç™¾åº¦ç»Ÿè®¡: https://tongji.baidu.com/
    # æ”¯æŒ:
    #   æ‰“èµè®°å½•: /about/
    # åè®®:
    #   Cookies: /cookies/
    #   ç”¨æˆ·åè®®: /privacy/
    #   ç‰ˆæƒåè®®: /copyright/

  randomlink: false
  privacy: # /privacy/
  license: # /license/
  links:
    - name: ä¸»é¢˜
      url: https://github.com/everfu/hexo-theme-solitude
    # - name: è®¢é˜…
    #   url: /atom.xml

errorpage:
  img: /img/404.avif
  text: =awa= é¡µé¢èµ°ä¸¢äº†
  recommendList: true

says:
  enable: false
  home_mini: false
  style: 1
  strip: 30

recent_comments:
  enable: false
  limit: 50 # âš ï¸waline ä»…æ”¯æŒæœ€å¤§50æ¡è¯„è®º / âš ï¸waline only supports a maximum of 50 comments
  cache: 0.2 # 1 = 1å¤© / 1 = 1 day
  page: /recentcomments/ # æœ€è¿‘è¯„è®ºé¡µé¢ / recent comments page
  img: /img/recent_c.avif # ä¸­æ§å°æ˜¾ç¤ºå›¾ç‰‡ï¼ˆä¸å¡«ä¸æ˜¾ç¤ºï¼‰ / image displayed in the console

envelope:
  enable: false
  line: 10 # æ˜¾ç¤ºè¡Œæ•°
  speed: 20 # æ’­æ”¾é€Ÿåº¦
  hover: true # é¼ æ ‡æ‚¬åœæš‚åœ
  loop: true # å¾ªç¯æ’­æ”¾
  page: /message/ # ç•™è¨€æ¿é¡µé¢ / message board page

meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r" #è‡ªå®šä¹‰api
music:
  enable: false
  id: 1994908354
  server: netease
  type: playlist
  volume: 0.8
  mutex: true

capsule:
  enable: false
  id: 8407304077
  server: netease
  type: playlist

keyboard:
  enable: false # æ˜¯å¦å¼€å¯é”®ç›˜æ§åˆ¶ / Whether to enable keyboard control
  list:
    # è¯´æ˜ï¼š
    # - name: æŒ‰é”®åç§°(name)
    #   key: æŒ‰é”®(Key)
    #   func: æ–¹æ³•(function)
    #   sco: scoå†…ç½®æ–¹æ³•(sco.'function')
    #   url: è·³è½¬é“¾æ¥(link)
    # ------------------
    # - name: å…³é—­å¿«æ·é”®åŠŸèƒ½
    #   key: K
    #   func: keyboard
    # - name: æ‰“å¼€ä¸­æ§å°
    #   key: A
    #   sco: showConsole
    # - name: æ’­æ”¾/æš‚åœéŸ³ä¹
    #   key: M
    #   sco: musicToggle
    # - name: æ‰“å¼€å‹æƒ…é“¾æ¥
    #   key: L
    #   url: /links/

copy:
  enable: true
  copyright: # Turn on Link copyright information after copying.ï¼ˆå¼€å¯åå°†åœ¨é»˜è®¤å¢åŠ ç‰ˆæƒä¿¡æ¯ï¼‰
    enable: true
    limit: 50 # å­—æ•° / word count

lazyload:
  enable: false
  field: site # post, site
  placeholder: /img/loading.avif
  errorimg: /img/error_load.avif

loading:
  fullpage: false
  pace: true

highlight:
  enable: true
  limit: 200 # ä»£ç è¡Œé«˜é™åˆ¶ / Code line limit
  copy: true # æ˜¯å¦å¼€å¯å¤åˆ¶æŒ‰é’® / Whether to enable the copy button
  expand: true # æ˜¯å¦é»˜è®¤å±•å¼€ / Whether to expand by default
  theme: default # default: é»˜è®¤ / mac : apple terminal
  color: default # default: é»˜è®¤  / solidity: solidity / dracula: dracula

lightbox: false
fancybox: false
mediumZoom: false

mermaid: false

OpenGraph:
  enable: false
  options:
    # twitter_card:
    # twitter_image:
    # twitter_id:
    # twitter_site:
    # google_plus:
    # fb_admins:
    # fb_app_id:

wordcount: false

busuanzi: false
busuanzi_use: 0 # 0: åŸç‰ˆ / 1: é’ç§¸(other: å…¶å®ƒè‡ªå®šç¾©çš„busuanziå¹³å°)

search:
  enable: false
  type: local # local: æœ¬åœ°æœç´¢ / algolia: Algoliaæœç´¢ / local: local search
  tags:
    # - Solitude
    # - Hexo
  algolia:
    # hits:
    #   per_page: 6
  local:
    preload: false
    CDN:

tianli_talk:
  enable: false
  title: æ™ºèƒ½å®¢æœä¸æœç´¢
  key: # è¯·å¡«å†™ä½ çš„key
  option:
post_ai:
  enable: false
  modelName: GPT 4
  key:
  talk: # æˆ‘æ˜¯ Efu å¼€å‘çš„æ‘˜è¦ç”ŸæˆåŠ©ç†EfuGPTï¼ŒEfuGPTåœ¨é™æ€éƒ¨ç½²æ—¶è¿›è¡Œæ‘˜è¦çš„æ’°å†™ï¼Œå¹¶ä¸”åœ¨è®¿å®¢è®¿é—®æ—¶é€šè¿‡EfuCorrectionè½¬è¯‘åçš„æ–‡æœ¬æ‘˜è¦å®ç°å·¥å…·ã€‚æˆ‘åœ¨è¿™é‡Œåªè´Ÿè´£å·²ç»ç”Ÿæˆçš„æ‘˜è¦æ˜¾ç¤ºï¼Œä½ æ— æ³•ä¸æˆ‘ç›´æ¥æ²Ÿé€šï¼Œä½†æˆ‘å¯ä»¥å›ç­”ä¸€äº›é¢„è®¾çš„é—®é¢˜ã€‚
  randomPost: false
  report: https://efu.me/
  tips: # æ­¤å†…å®¹æ ¹æ®æ–‡ç« ç”Ÿæˆï¼Œå¹¶ç»è¿‡äººå·¥å®¡æ ¸ï¼Œä»…ç”¨äºæ–‡ç« å†…å®¹çš„è§£é‡Šä¸æ€»ç»“

katex:
  enable: false
  per_page: false # æ˜¯å¦åœ¨æ¯é¡µéƒ½åŠ è½½ / Whether to load on each page
  copytex: false # æ˜¯å¦å¼€å¯å¤åˆ¶å…¬å¼ / Whether to enable copy formula

comment:
  use: # waline, twikoo, valine, artalk, giscus
  commentBarrage: false # çƒ­è¯„å¼€å…³ / Hot comment switch
  lazyload: false # æ‡’åŠ è½½
  count: false # è¯„è®ºæ•°å±•ç¤º
  pv: false # æ˜¯å¦ä½¿ç”¨è¯„è®ºç»Ÿè®¡é¡µé¢è®¿é—®
  avatar: https://cravatar.cn # Gravatar link
  hot_tip: # å¤šäººäº’åŠ¨
    enable: false # å¼€å¯åå°†åœ¨æ–‡ç« åˆ—è¡¨æ˜¾ç¤ºå¤šäººäº’åŠ¨
    count: 3 # è®¾ç½®å¤§äºå¤šå°‘è¯„è®ºæ—¶æ˜¾ç¤º
twikoo: # https://twikoo.js.org/
  envId: # url: https://twikoo.sondy.top/
  region: # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œè…¾è®¯äº‘ç¯å¢ƒå¡« ap-shanghai æˆ– ap-guangzhouï¼›Vercel ç¯å¢ƒä¸å¡«
  style: true # Use custom styles when turned on / å¼€å¯åä½¿ç”¨è‡ªå®šä¹‰æ ·å¼
  accessToken: # AccessToken
  option: # twikoo option
waline: # https://waline.js.org/
  envId: # url: https://waline.wzsco.top
  pageview: false # æ˜¯å¦å¼€å¯é¡µé¢è®¿é—®é‡ç»Ÿè®¡ / Whether to enable page access statistics
  option: # walineé…ç½®é¡¹ / waline configuration item
valine:
  appId: # leancloud application app id
  appKey: # leancloud application app key
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  avatar: # https://valine.js.org/avatar.html
  visitor: false
  style: true # Use custom styles when turned on / å¼€å¯åä½¿ç”¨è‡ªå®šä¹‰æ ·å¼
  option: # options list
artalk:
  server: # server url / åç«¯åœ°å€
  site: # site name / ç«™ç‚¹å
  option: # options
giscus:
  repo: # GitHub ä»“åº“åç§° / GitHub repository name
  repo_id: # GitHub ä»“åº“ID / GitHub repository ID
  category_id: # GitHub ä»“åº“åˆ†ç±»ID / GitHub repository category ID
  theme:
    light: light
    dark: dark
  option:

console:
  enable: false # å¼€å¯åæ˜¾ç¤ºä¸­æ§å°
  recentComment: # å¼€å¯åæ˜¾ç¤ºæœ€è¿‘è¯„è®º
    enable: false # å¼€å¯å‰è¯·å…ˆé…ç½®è¯„è®º
    storage: .2 # ç¼“å­˜æ—¶é—´
  card:
    tags: true # å¼€å¯åæ˜¾ç¤º æ ‡ç­¾
    archive: true # å¼€å¯åæ˜¾ç¤º å½’æ¡£

verify_site:
  # - name: google-site-verification
  #   content: xxxxxx
  # - name: baidu-site-verification
  #   content: xxxxxxx

css_prefix: false

font:
  font-size: 16px
  code-font-size: 16px
  font-family: "PingFang SC, Hiragino Sans GB, Microsoft YaHei"
  code-font-family: '"monospace", monospace'

extends:
  head:
    # åœ¨headä¸­æ’å…¥ / Insert in head
    # - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
  body:
    # åœ¨bodyä¸­æ’å…¥ / Insert in body

pwa:
  enable: false
  manifest: /manifest.json # manifest.json æ–‡ä»¶è·¯å¾„
  theme_color: "#006a73" # ä¸»é¢˜é¢œè‰²
  mask_icon: /img/pwa/favicon.ico # é®ç½©å›¾æ ‡
  apple_touch_icon: /img/pwa/favicon.ico # è‹¹æœè§¦æ‘¸å›¾æ ‡
  bookmark_icon: /img/pwa/favicon.ico # ä¹¦ç­¾å›¾æ ‡
  favicon_32_32: /img/pwa/favicon_32.ico # 32x32å›¾æ ‡
  favicon_16_16: /img/pwa/favicon_16.ico # 16x16å›¾æ ‡

google_adsense:
  enable: false
  auto_ads: false # è‡ªåŠ¨å¹¿å‘Šå…³é—­ååˆ™ä¸ºæ‰‹åŠ¨å¹¿å‘Š / After auto ads are turned off, it is manual ads
  enable_page_level_ads: true # é¡µé¢çº§å¹¿å‘Š / Page-level ads
  aside_card: true # ä¾§è¾¹æ å¡ç‰‡å¹¿å‘Š / Sidebar card adsï¼ˆå¼€å¯åè‡ªè¡Œåˆ°éœ€è¦æ·»åŠ çš„é¡µé¢ä½¿ç”¨ï¼šadsï¼‰
  post_card: true # æ–‡ç« å¡ç‰‡å¹¿å‘Š / Post card adsï¼ˆé¦–é¡µæ–‡ç« åˆ—è¡¨ï¼‰
  post_content: true # æ–‡ç« å†…å®¹å¹¿å‘Š / Post content adsï¼ˆæ–‡ç« å†…å®¹åº•éƒ¨å¹¿å‘Šï¼‰
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js # è°·æ­Œå¹¿å‘Šjs / Google Adsense js
  client: # ca-pub-XXXXXXXXXXXXXX
  slot: # 4236388782

right_menu:
  enable: false
  commentBarrage: false # æ˜¯å¦æ˜¾ç¤ºçƒ­è¯„å¼€å…³ / Whether to display the hot comment switch.
  translate:
    enable: false
    defaultEncoding: 2 # 1: é»˜è®¤ç¹ä½“ 2: é»˜è®¤ç®€ä½“
    translateDelay: 0 # é¦–æ¬¡åŠ è½½ç¿»è¯‘è¿Ÿç–‘æ—¶é—´
  custom_list:
    # - name: éšæœºçŸ­æ–‡
    #   click: toRandomPost()
    #   id: menu-randomPost
    #   class:
    #   icon: fas fa-tower-broadcast
    # - name: å…¨éƒ¨åˆ†ç±»
    #   click: pjax.loadUrl('/categories/') # å¤–é“¾ç”¨ window.openï¼Œpjax æ— æ³•è¯·æ±‚è·¨åŸŸå†…å®¹
    #   id:
    #   class:
    #   icon: fas fa-clone
    # - name: å…¨éƒ¨æ ‡ç­¾
    #   click: pjax.loadUrl('/tags/')
    #   id:
    #   class:
    #   icon: fas fa-tags

memorial:
  enable: false
  # æ—¥æœŸ, (M-D)
  # Date, (M-D)
  # eg: 7-7, 9-18, 12-13 ...
  date:
    - 7-7 # ä¸ƒä¸ƒäº‹å˜
    - 9-18 # ä¹ä¸€å…«äº‹å˜
    - 12-13 # å—äº¬å¤§å± æ€å›½å®¶å…¬ç¥­æ—¥

lure:
  enable: false
  jump: 404 Not Found
  back: ãƒ¾(â‰§âˆ‡â‰¦*)ã‚å˜¿å˜¿ï¼Œä¸Šå½“äº†å§

expire:
  enable: false
  time: 30 # days
  position: top # top / bottom
  text_prev: æœ¬æ–‡å·²äº
  text_next: å¤©å‰è¿‡æœŸï¼Œå¦‚æœå†…å®¹ä¸ç¬¦ï¼Œè¯·è”ç³»ç«™é•¿æ›´æ–°ã€‚

background:
  enable: false
  opacity: .2
  dark: https://bu.dusays.com/2023/09/29/651685ce667d1.jpg
  light: https://bu.dusays.com/2023/09/29/651685cc18d39.jpg

CDN:
  internal: local
  third_party: cdnjs
  version: true
  custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
  option:
    solitude_css: https://cdn2.codesign.qq.com/icons/7pOrz0WXB5ZWJPX/latest/iconfont.css
    busuanzi_qj_js: https://pv.lemonso.com/js
    # algolia_search:
    # instantsearch:
    # pjax:
    # twikoo:
    # waline_js:
    # waline_css:
    # katex:
    # katex_copytex:
    # lazyload:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # pace_js:
    # swiper_css:
    # swiper_js:
    # busuanzi_js:
    # snackbar_js: